### PR TITLE
Fix empty user_name labels in job_info metric

### LINKED ISSUE #1238: [Soperator exporter] Metric job_info: user_name label is empty for all users except root
It is requored to mount jail and use users infromation from there.

### PR DESCRIPTION
**Pull request by theyoprst**
## Summary
- Add user_id label to job_info metric in soperator exporter for fallback when user_name is empty
- Enable REST container to access jail passwd files for username resolution

Closes https://github.com/nebius/soperator/issues/1238

### CODE REVIEW

File: images/restd/slurmrestd_entrypoint.sh [hunk 1]
```diff
@@ -2,6 +2,14 @@
 
 set -e # Exit immediately if any command returns a non-zero error code
 
+echo "Link users from jail"
+for file in passwd group shadow gshadow; do
+  rm -f /etc/$file
```
Comment (asteny) [inline images/restd/slurmrestd_entrypoint.sh:7]: In all other images we removed users in Docker file and link them in entrypoint

Comment (theyoprst) [reply images/restd/slurmrestd_entrypoint.sh:7]: Why is it so important?

Comment (theyoprst) [reply images/restd/slurmrestd_entrypoint.sh:7]: > In all other images we removed users in Docker file and link them in entrypoint

I don't think it's good idea to split /etc/passwd file creation by different files, that's why I did it in one place. Any reasons I should split it?

**Review by rdjjke — APPROVED** [review]

File: images/restd/slurmrestd_entrypoint.sh (hunk 1 above)
Comment (asteny) [reply images/restd/slurmrestd_entrypoint.sh:7]: My point is not about splitting... I think we need to do that in one way in all places)
